variable "bucket_domain" {}
variable "web_acl_id" {}
variable "env" {}

# Key group ID from CloudFront → Key management → Key groups
# CloudFront uses this to verify signed URLs generated by Lambda
variable "cf_key_group_id" {}
