variable "region" {
  default = "us-east-1"
}

variable "env" {
  default = "dev"
}

# CloudFront key pair ID for signed URL generation
# Create in AWS Console → CloudFront → Key management → Key pairs
variable "cf_key_pair_id" {
  description = "CloudFront key pair ID used to sign streaming URLs"
  default     = ""
}

# CloudFront private key PEM — passed in via GitHub Actions secret TF_VAR_cf_private_key
# Never commit this value — set it as a secret in GitHub Actions
variable "cf_private_key" {
  description = "CloudFront private key PEM for signing URLs"
  sensitive   = true
  default     = ""
}

# CloudFront key group ID — created in AWS Console → CloudFront → Key management → Key groups
# Used by CloudFront to verify signed URLs generated by Lambda
variable "cf_key_group_id" {
  description = "CloudFront key group ID for signed URL verification"
  default     = ""
}
